# Configuración Básica del Servidor
server.port=8085
spring.application.name=MusicRights
spring.profiles.active=prod
logging.level.org.springframework=ERROR

# Conexión a Base de Datos MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://musicrights-db:3306/musicrights
spring.datasource.username=musicrights_user
spring.datasource.password=${MUSICRIGHTS_DATABASE_PASSWORD}

# Configuración de Hibernate y JPA (Forzar creación de tablas)
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=create

# Forzar la ejecución del script data.sql en Perfil Prod
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# AWS S3
aws.s3.bucket=${AWS_S3_BUCKET:music-rights-pdf}
aws.s3.region=${AWS_S3_REGION:us-east-1}