name: Integration tests with Newman

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  newman-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn package -DskipTests
      - run: docker compose up -d --build
        env:
          # Enchufamos ls variables en el sistema
          MARIADB_USER: musicrights_user
          MARIADB_DATABASE: musicrights
          MARIADB_ROOT_PASSWORD: root_root
          PROFILE: prod

          MUSICRIGHTS_DATABASE_PASSWORD: root_password
      - run: sleep 30
      - run: docker logs musicrights-api
      - run: docker ps
      - run: npm install -g newman
      - run: newman run "MusicRights API.postman_collection.json" -e Local.postman_environment.json --env-var "HOST=localhost:8085"